version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .${NODE_ENV}.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${LOCAL_CORE_PORT}:${LOCAL_CORE_PORT}
      - 9229:9229
    command: npm run ${COMMAND_START}
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .${NODE_ENV}.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${LOCAL_POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: